### ISSUE TITLE
Expose status / performance metrics to storm

### ISSUE THREAD

**Issue by akaIDIOT** [NetherlandsForensicInstitute/kafka-spout#5]
Performance metrics aside those already gathered by storm would be useful to tweak performance and allow insight into possible runtime issues.

**Comment by siddharthU** [comment]
Hi, i am trying to submit a topology based on your project . I seem to do fine in localcluster however, in the distributed mode the workers are not starting and i am getting an error "Netty reconnect workername" over n over again. can you pls help?

**Comment by akaIDIOT** [comment]
Project to be archived.
